# Generated by Django 5.1.1 on 2024-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_memberprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
