# Generated by Django 5.1.1 on 2024-10-07 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_member_groups_alter_member_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 10, 7, 20, 50, 49, 882729, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(default="avatars/image.png", upload_to="avatars/"),
        ),
    ]
