# Generated by Django 5.1.1 on 2024-10-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_date_joined_alter_customuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
            ],
        ),
    ]
