# Generated by Django 4.2.16 on 2024-10-18 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attraction_name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=100, unique=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="members.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NormGroupID", models.CharField(max_length=150, null=True)),
                ("tourname", models.CharField(max_length=150, null=True)),
                ("tourlink", models.CharField(max_length=150, null=True)),
                ("tourimage", models.CharField(max_length=150, null=True)),
                ("tourday", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=0, max_digits=8)),
                ("earlierGoDate", models.CharField(max_length=500, null=True)),
                ("create_date", models.DateField(default=django.utils.timezone.now)),
                ("renew_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("tourSpecial", models.CharField(max_length=500, null=True)),
                ("goDate", models.CharField(max_length=2000, null=True)),
                ("day", models.CharField(max_length=50, null=True)),
                ("travelPoint", models.CharField(max_length=50, null=True)),
                ("breakfast", models.CharField(max_length=50, null=True)),
                ("lunch", models.CharField(max_length=50, null=True)),
                ("dinner", models.CharField(max_length=50, null=True)),
                ("hotel", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TourSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.site"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toursites_as_tour",
                        to="members.tour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourAttraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.attraction",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourattractions_as_tour",
                        to="members.tour",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tour",
            name="attraction",
            field=models.ManyToManyField(
                related_name="tours_as_attraction",
                through="members.TourAttraction",
                to="members.attraction",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.company"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="gosite",
            field=models.ManyToManyField(
                related_name="tours_as_gosite",
                through="members.TourSite",
                to="members.site",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="toursite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours_as_toursite",
                to="members.site",
            ),
        ),
    ]
