# Generated by Django 4.2.16 on 2024-10-24 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_tourorder_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourorder",
            name="godate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tourorder",
            name="gosite",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
