# Generated by Django 5.1.1 on 2024-10-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_tourorder_godate_tourorder_gosite"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(default="Unknown", max_length=100)),
                ("from_station", models.CharField(max_length=100)),
                ("to_station", models.CharField(max_length=100)),
                ("departure_time", models.DateField()),
                ("passenger_name", models.CharField(max_length=100)),
                ("passenger_ID", models.CharField(default=False, max_length=30)),
                ("go_time", models.CharField(default=False, max_length=30)),
                ("order_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
