# Generated by Django 4.2.16 on 2024-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_ticketorder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketorder",
            name="order_sum",
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="seat_number",
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="ticket_number",
            field=models.CharField(default=False, max_length=30),
        ),
    ]
