# Generated by Django 4.2.16 on 2024-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_ticketorder_order_sum_ticketorder_seat_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketorder",
            name="order_sum",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="ticketorder",
            name="seat_number",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="ticketorder",
            name="ticket_number",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
