# Generated by Django 4.2.16 on 2024-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0020_alter_ticketorder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketorder",
            name="arrive_time",
            field=models.CharField(default=False, max_length=30),
        ),
    ]
